"""
EtiquetadorZPL - Módulos del sistema
"""

# Constantes
from constants import (
    APP_NAME,
    APP_VERSION,
    ALLOWED_EXTENSIONS,
    ALLOWED_ZPL_EXTENSIONS,
    ALLOWED_IMAGE_EXTENSIONS,
    MAX_FILE_SIZE_BYTES,
    MAX_ZIP_SIZE_BYTES,
    MAX_TXT_SIZE_BYTES,
    MAX_ZPL_SIZE_BYTES,
    MAX_CONCURRENT_FILES,
    DEFAULT_COPIES,
    MAX_COPIES,
    MIN_COPIES,
    JOB_STATUS,
    ERROR_MESSAGES,
    SUCCESS_MESSAGES,
    LOG_FORMAT,
    LOG_DATE_FORMAT,
    MAX_MEMORY_PERCENT,
    MAX_CPU_PERCENT,
    MAX_DISK_PERCENT,
    DANGEROUS_FILENAMES,
    DANGEROUS_FILENAME_CHARS,
    FORBIDDEN_ZPL_COMMANDS,
    MAX_RETRY_ATTEMPTS,
    RETRY_BACKOFF_FACTOR,
    RETRY_INITIAL_DELAY,
    DEFAULT_LABEL_WIDTH_MM,
    DEFAULT_LABEL_HEIGHT_MM,
)

# Excepciones
from exceptions import (
    EtiquetadorZPLException,
    FileException,
    FileNotFoundException,
    FileTooLargeException,
    InvalidExtensionException,
    InvalidFilenameException,
    PrinterException,
    PrinterNotFoundException,
    PrinterNotConfiguredException,
    PrinterConnectionException,
    ZPLException,
    InvalidZPLException,
    ZPLSanitizeException,
    DatabaseException,
    DatabaseConnectionException,
    DatabaseQueryException,
    APIException,
    APIRateLimitException,
    APIValidationException,
    ConfigException,
    ConfigNotFoundException,
    ConfigValidationException,
    PermissionException,
    PermissionDeniedException,
    HistoryException,
    ExceptionHandler,
)

# Utilidades
from utils import (
    retry,
    async_retry,
    log_call,
    timing,
    synchronized,
    deprecated,
    temporary_file,
    temporary_directory,
    locked_resource,
    Timer,
    get_file_hash,
    ensure_directory,
    safe_filename,
    format_bytes,
    format_duration,
    parse_bool,
    deep_merge,
    load_json_safe,
    save_json_safe,
    chunks,
    clamp,
    is_valid_path,
    is_safe_path,
    is_valid_extension,
)

# Rate Limiter
from rate_limiter import (
    RateLimitConfig,
    CircuitBreakerConfig,
    TokenBucket,
    RateLimiter,
    CircuitBreaker,
    CircuitBreakerOpenError,
    CircuitBreakerManager,
    rate_limiter,
    circuit_breaker_manager,
    get_rate_limiter,
    get_circuit_breaker,
)

# Base de datos (importación tardía para evitar ciclos)
def get_database():
    """Obtener instancia de base de datos"""
    from database import db
    return db

__all__ = [
    # Constantes
    'APP_NAME',
    'APP_VERSION',
    'ALLOWED_EXTENSIONS',
    'ALLOWED_ZPL_EXTENSIONS',
    'ALLOWED_IMAGE_EXTENSIONS',
    'MAX_FILE_SIZE_BYTES',
    'MAX_ZIP_SIZE_BYTES',
    'MAX_TXT_SIZE_BYTES',
    'MAX_ZPL_SIZE_BYTES',
    'MAX_CONCURRENT_FILES',
    'DEFAULT_COPIES',
    'MAX_COPIES',
    'MIN_COPIES',
    'JOB_STATUS',
    'ERROR_MESSAGES',
    'SUCCESS_MESSAGES',
    'LOG_FORMAT',
    'LOG_DATE_FORMAT',
    'MAX_MEMORY_PERCENT',
    'MAX_CPU_PERCENT',
    'MAX_DISK_PERCENT',
    'DANGEROUS_FILENAMES',
    'DANGEROUS_FILENAME_CHARS',
    'FORBIDDEN_ZPL_COMMANDS',
    'MAX_RETRY_ATTEMPTS',
    'RETRY_BACKOFF_FACTOR',
    'RETRY_INITIAL_DELAY',
    'DEFAULT_LABEL_WIDTH_MM',
    'DEFAULT_LABEL_HEIGHT_MM',
    
    # Excepciones
    'EtiquetadorZPLException',
    'FileException',
    'FileNotFoundException',
    'FileTooLargeException',
    'InvalidExtensionException',
    'InvalidFilenameException',
    'PrinterException',
    'PrinterNotFoundException',
    'PrinterNotConfiguredException',
    'PrinterConnectionException',
    'ZPLException',
    'InvalidZPLException',
    'ZPLSanitizeException',
    'DatabaseException',
    'DatabaseConnectionException',
    'DatabaseQueryException',
    'APIException',
    'APIRateLimitException',
    'APIValidationException',
    'ConfigException',
    'ConfigNotFoundException',
    'ConfigValidationException',
    'PermissionException',
    'PermissionDeniedException',
    'HistoryException',
    'ExceptionHandler',
    
    # Utilidades
    'retry',
    'async_retry',
    'log_call',
    'timing',
    'synchronized',
    'deprecated',
    'temporary_file',
    'temporary_directory',
    'locked_resource',
    'Timer',
    'get_file_hash',
    'ensure_directory',
    'safe_filename',
    'format_bytes',
    'format_duration',
    'parse_bool',
    'deep_merge',
    'load_json_safe',
    'save_json_safe',
    'chunks',
    'clamp',
    'is_valid_path',
    'is_safe_path',
    'is_valid_extension',
    
    # Rate Limiter
    'RateLimitConfig',
    'CircuitBreakerConfig',
    'TokenBucket',
    'RateLimiter',
    'CircuitBreaker',
    'CircuitBreakerOpenError',
    'CircuitBreakerManager',
    'rate_limiter',
    'circuit_breaker_manager',
    'get_rate_limiter',
    'get_circuit_breaker',
    
    # Base de datos
    'get_database',
]

